# Generated by Django 3.0.5 on 2020-04-21 19:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('address_number', models.CharField(max_length=3)),
                ('country_code', models.CharField(max_length=4)),
                ('hourly_rate', models.IntegerField()),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('opening_time', models.CharField(max_length=5)),
                ('closing_time', models.CharField(max_length=5)),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_time', models.DateTimeField(null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Car')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.Garage')),
            ],
        ),
    ]
