# Generated by Django 3.0.5 on 2020-04-22 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarageOwner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.Garage')),
            ],
        ),
    ]
