# Generated by Django 3.0.5 on 2020-04-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_garageowner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GarageOwner',
        ),
    ]
