# Generated by Django 3.0.5 on 2020-05-03 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_auto_20200425_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='car',
        ),
    ]
