language: python

python:
  - "3.7"
env:
  - SECRET_KEY="TEST"
install:
  - cd api/ && pipenv install

script:
  - python manage.py makemigrations --merge --noinput
  - python manage.py test --noinput
