# Generated by Django 3.0.5 on 2020-04-22 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('iban', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=3)),
                ('zip_code', models.CharField(max_length=4)),
                ('date_became_customer', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
