# Generated by Django 3.0.5 on 2020-04-25 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200425_1332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Costumer',
        ),
    ]
