# Generated by Django 3.0.5 on 2020-04-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200425_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='is_garage_owner',
            field=models.BooleanField(default=False),
        ),
    ]
