# Generated by Django 3.0.5 on 2020-05-02 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_transactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='user_id',
            new_name='user',
        ),
    ]
