# Generated by Django 3.0.5 on 2020-05-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_plate_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
