# Generated by Django 3.0.5 on 2020-05-04 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merge_20200504_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='check_in_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='check_out_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
