# Generated by Django 3.0.5 on 2020-05-06 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merge_20200504_1647'),
        ('users', '0013_auto_20200504_2002'),
    ]

    operations = [
    ]
